# Generated by Django 5.1.2 on 2024-10-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_created_on_department_updated_on'),
        ('school', '0002_school_created_on_school_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='school.school'),
        ),
    ]
