# Generated by Django 5.1.2 on 2024-10-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='rating',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
