# Generated by Django 5.1.2 on 2024-10-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teacher_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='chemistry_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='maths_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='physics_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
