# Generated by Django 5.1.2 on 2024-10-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_student_id_remove_student_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_teachers',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='chemistry_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='maths_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='physics_marks',
            field=models.IntegerField(),
        ),
    ]
