# Generated by Django 5.1.2 on 2024-10-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_student_percentage_student_total_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='total_marks',
        ),
    ]
