# Generated by Django 5.1.2 on 2024-10-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_student_percentage_remove_student_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
