# Generated by Django 5.1.2 on 2024-10-22 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myapp.teacher'),
        ),
    ]
