# Generated by Django 5.1.2 on 2024-10-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_student_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='perfomance',
            field=models.FloatField(default=0.0),
        ),
    ]
