# Generated by Django 5.1.2 on 2024-10-22 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_teacher_perfomance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='perfomance',
        ),
    ]
