# Generated by Django 5.1.2 on 2024-10-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_teacher_perfomance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='perfomance',
            field=models.FloatField(default=0.0),
        ),
    ]
