# Generated by Django 5.1.2 on 2024-10-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_teacher_perfomance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='perfomance',
            new_name='performance',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
