# Generated by Django 5.1.2 on 2024-10-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_perfomance_teacher_performance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_teachers',
        ),
    ]
