# Generated by Django 5.1.2 on 2024-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_student_class_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_teachers',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
