# Generated by Django 5.1.2 on 2024-10-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_teacher_dept_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='dept_id',
            new_name='dept_name',
        ),
    ]
