# Generated by Django 5.1.2 on 2024-10-24 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_department_created_on_department_updated_on'),
        ('myapp', '0028_rename_dept_id_teacher_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department'),
        ),
    ]
